apiVersion: v1
kind: Service
metadata:
  name: pickpix-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 30081
      name: https
  selector:
    app: pickpix-app
