apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpix-app
spec:
  selector:
    matchLabels:
      app: pickpix-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pickpix-app
    spec:
      hostname: pickpix
      containers:
        - image: localhost:5000/pickpix-app:latest
          name: pickpix-app
          imagePullPolicy: Always
          command: ["/pickpix-app/start_httpd.sh"]
          #command: ["tail", "-f", "/dev/null"]
