apiVersion: v1
kind: Service
metadata:
  name: pickpix-app
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: pickpix-app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpix-app
spec:
  selector:
    matchLabels:
      app: pickpix-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pickpix-app
    spec:
      hostname: pickpix
      containers:
      - image: pickpix-app:latest
        name: pickpix-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          hostPort: 8080
        - containerPort: 443
          hostPort: 9443
        command: ["/pickpix-app/start_httpd.sh"]
        #command: ["tail", "-f", "/dev/null"]
