apiVersion: v1
kind: Service
metadata:
  name: pickpix-app
spec:
  ports:
  - port: 80
  selector:
    app: pickpix-app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickpix-app
spec:
  selector:
    matchLabels:
      app: pickpix-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pickpix-app
    spec:
      containers:
      - image: pickpix-app:latest
        name: pickpix-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        command:
        - tail
        - "-f"
        - /dev/null
