# Generated by Django 4.0.3 on 2022-04-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_index', models.IntegerField(default=0, unique=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pickpix.picktoken')),
            ],
        ),
    ]
