# Generated by Django 4.0.3 on 2022-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickpix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picktoken',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
