FROM apache-django-base:latest

# Setup apache and django
WORKDIR /pickpix-app/website

#RUN python3 manage.py runmodwsgi --setup-only --port=80 \
#    --user www-data --group www-data \
#    --server-root=/pickpix-app/website
