name: Django CI

on:
  push:
    branches:
      - master

jobs:
  job_name:
    runs-on: [control-center]
    steps:
      - uses: actions/checkout@v1
      - name: Build and deploy
        working-directory: ./pickpix-app
        run: |
          docker build --tag pickpix-app:latest . --no-cache
          docker save pickpix-app > pickpix-app_image.tar
          microk8s ctr image import pickpix-app_image.tar
          microk8s.kubectl replace -f setup/pickpix-app-deployment.yaml --force
